linters:
  rubocop: 
    Exclude:     
    - 'db/*'     
    - 'config/**/*'     
    - 'script/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    Metrics/LineLength:
      Max: 90
    Style/Documentation:
      Enabled: false
    Style/FrozenStringLiteralComment:
      Enabled: false
