linters:
  Rubocop:
    enabled: true
    rubocop_config:
      Rails:
        Enabled: true
      Rails/Present:
        Enabled: true
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false